 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/judgements", type: :request do
  # Judgement. As you add validations to Judgement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Judgement.create! valid_attributes
      get judgements_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      judgement = Judgement.create! valid_attributes
      get judgement_url(judgement)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_judgement_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      judgement = Judgement.create! valid_attributes
      get edit_judgement_url(judgement)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Judgement" do
        expect {
          post judgements_url, params: { judgement: valid_attributes }
        }.to change(Judgement, :count).by(1)
      end

      it "redirects to the created judgement" do
        post judgements_url, params: { judgement: valid_attributes }
        expect(response).to redirect_to(judgement_url(Judgement.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Judgement" do
        expect {
          post judgements_url, params: { judgement: invalid_attributes }
        }.to change(Judgement, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post judgements_url, params: { judgement: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested judgement" do
        judgement = Judgement.create! valid_attributes
        patch judgement_url(judgement), params: { judgement: new_attributes }
        judgement.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the judgement" do
        judgement = Judgement.create! valid_attributes
        patch judgement_url(judgement), params: { judgement: new_attributes }
        judgement.reload
        expect(response).to redirect_to(judgement_url(judgement))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        judgement = Judgement.create! valid_attributes
        patch judgement_url(judgement), params: { judgement: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested judgement" do
      judgement = Judgement.create! valid_attributes
      expect {
        delete judgement_url(judgement)
      }.to change(Judgement, :count).by(-1)
    end

    it "redirects to the judgements list" do
      judgement = Judgement.create! valid_attributes
      delete judgement_url(judgement)
      expect(response).to redirect_to(judgements_url)
    end
  end
end
